#! /usr/bin/python

import numpy as np

#Set the number of random points:
num=200

# Set the range of x and y and ra and dec for the random catalog.
x1=-100
y1=-100
x2=1000
y2=1000
ra1=149
dec1=1.45
ra2=151
dec2=2.95

# Make the array with random values:
a=np.random.rand(num, 5)

# Fill the first one with row numbers:
for i in range(0, num):
    a[i, 0]=i+1;

# Fill each column:
a[:,1]=a[:,1]*(x2-x1)+x1
a[:,2]=a[:,2]*(y2-y1)+y1
a[:,3]=a[:,3]*(ra2-ra1)+ra1
a[:,4]=a[:,4]*(dec2-dec1)+dec1

np.savetxt("randcat.txt", a, fmt="%-10d %-15.3f %-15.3f %-15.8f %-15.8f",
           header="Random catalog generated by makerandomcat.py\n"
           +"Column 0: ID\n"+"Column 1: X\n"
           +"Column 2: Y\n"+"Column 3: RA\n"+"Column 4: Dec.")
